const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
const path=require('node:path');
const store=new Map();let fail=false;
const ctx={window:{},crypto,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(fail)throw Error('quota');store.set(k,v);}}};
vm.createContext(ctx);
for(const file of ['apps-field-values.js','apps-data-model.js']){vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',file),'utf8'),ctx);Object.assign(ctx,ctx.window);}
const M=ctx.AppsDataModel;
const access={space:'team',teamId:'team-demo'},input={user:'zhang',appId:'sales',table:'customers',scope:'team',access};
let r=M.rows('zhang','sales','customers','team',access).find(r=>r.owner==='zhou');
assert.equal(M.permissions('wangning','sales','customers',r,'team',access).update,false);
assert.equal(M.permissions('linxiao','sales','customers',r,'team',access).update,true);
assert.equal(M.permissions('chen','sales','customers',r,'mine',{space:'personal'}).create,true);
assert.equal(M.permissions('chen','leads','actions',null,'all',{space:'personal'}).create,false,'App creator is not automatically the table owner');
assert.throws(()=>M.mutate({...input,user:'wangning'},'update',{id:r.id,version:r.version,values:r.values}),/没有操作权限/);
assert.throws(()=>M.mutate({...input,access:{space:'team',teamId:'other'}},'update',{id:r.id,version:r.version,values:r.values}),/没有操作权限/);
const updated=M.mutate(input,'update',{id:r.id,version:r.version||r.updated,values:['编辑验证',...r.values.slice(1)]});
M.reload();assert.equal(M.rows('zhang','sales','customers','team',access).find(x=>x.id===r.id).values[0],'编辑验证');
assert.equal(updated.owner,'zhou','editing preserves system ownership');
assert.throws(()=>M.mutate(input,'update',{id:r.id,version:r.version||r.updated,values:r.values}),/已被更新/);
assert.throws(()=>M.mutate(input,'create',{values:['','','','']}),/请填写客户名称/);
const created=M.mutate(input,'create',{values:['新增测试','北京','测试','重点客户']});
assert.equal(created.owner,'zhang');assert.equal(created.teamId,'team-demo');
fail=true;
assert.throws(()=>M.mutate(input,'delete',{id:created.id,version:created.version}),/保存失败/);
assert.ok(M.rows('zhang','sales','customers','team',access).some(x=>x.id===created.id));
fail=false;M.mutate(input,'delete',{id:created.id,version:created.version});M.reload();
assert.ok(!M.rows('zhang','sales','customers','team',access).some(x=>x.id===created.id));
assert.equal(M.latestActivity('zhang','sales','team',access).actor,'zhang');
const numeric={...input,table:'opportunities'};
assert.throws(()=>M.mutate(numeric,'create',{values:['测试','跟进','abc','2026-09-22']}),/有效数字/);
assert.throws(()=>M.mutate(numeric,'create',{values:['测试','跟进',1,'2026-02-30']}),/有效的日期/);
console.log('PASS: manual CRUD, table ACL, persistence, validation, conflict and failure rollback.');
